import { useCallback, useEffect, useState } from "react";
import { Button, Card, EmptyState, ErrorState, Input, LoadingState, Modal, PageHeader, Select, StatusBadge, Textarea } from "../components/ui";

const blank = { internal_name:"", title:"", subtitle:"", campaign_type:"announcement", body_content:"", price_text:"", regular_price_text:"", call_to_action_label:"", priority:0, starts_at:"", ends_at:"", schedule_mode:"immediate", end_mode:"none", target_all_clients:true, target_client_ids:[], popup_enabled:false, popup_summary:"", call_to_action_url:"" };
const labels = { announcement:"Announcement", promotion:"Promotion", new_service:"New Service", maintenance_notice:"Maintenance Notice", tip:"Tip", featured_project:"Featured Project", important_notice:"Important Notice" };
const icons = { announcement:"✦", promotion:"%", new_service:"+", maintenance_notice:"⚙", tip:"i", featured_project:"★", important_notice:"!" };
const dt = value => value ? new Date(value).toLocaleString() : "Not set";
const localInput = value => {
  if (!value) return "";
  const date = new Date(value.endsWith("Z") ? value : `${value}Z`);
  const local = new Date(date.getTime() - date.getTimezoneOffset() * 60000);
  return local.toISOString().slice(0, 16);
};
const utcInput = value => value ? new Date(value).toISOString() : null;

export default function Campaigns() {
  const [items,setItems]=useState([]), [clients,setClients]=useState([]), [loading,setLoading]=useState(true);
  const [error,setError]=useState(null), [editor,setEditor]=useState(null), [preview,setPreview]=useState(null), [deleting,setDeleting]=useState(null), [resetTarget,setResetTarget]=useState(null), [saving,setSaving]=useState(false), [stats,setStats]=useState({}), [notice,setNotice]=useState(null);
  const activeClients=clients.filter(client=>String(client.status).toLowerCase()==="active");
  const selectedActiveCount=editor?activeClients.filter(client=>editor.target_client_ids.includes(client.id)).length:0;
  const recipientCount=editor?(editor.target_all_clients?activeClients.length:selectedActiveCount):0;
  const shortWindow=!!(editor?.end_mode==="at"&&editor.ends_at&&((new Date(editor.ends_at)-new Date(editor.schedule_mode==="later"&&editor.starts_at?editor.starts_at:Date.now()))<3600000));
  const campaignRecipients=campaign=>campaign.target_all_clients?activeClients.length:activeClients.filter(client=>campaign.target_client_ids.includes(client.id)).length;
  const load=useCallback(async()=>{try{const [a,b,s]=await Promise.all([fetch("/api/admin/campaigns",{credentials:"include"}),fetch("/api/admin/campaign-target-clients",{credentials:"include"}),fetch("/api/admin/campaign-popup-stats",{credentials:"include"})]);if(!a.ok||!b.ok||!s.ok)throw new Error("Unable to load campaigns");setItems((await a.json()).campaigns);setClients(await b.json());setStats((await s.json()).campaigns||{});setError(null)}catch(e){setError(e.message)}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);
  const edit=item=>setEditor(item?{...item,starts_at:localInput(item.starts_at),ends_at:localInput(item.ends_at),schedule_mode:item.starts_at?"later":"immediate",end_mode:item.ends_at?"at":"none"}:{...blank});
  const payload=form=>{const {schedule_mode,end_mode,...values}=form;return {...values,priority:Number(form.priority)||0,starts_at:schedule_mode==="later"?utcInput(form.starts_at):null,ends_at:end_mode==="at"?utcInput(form.ends_at):null}};
  const save=async(publish=false)=>{if(publish&&!editor.target_all_clients&&!editor.target_client_ids.length){setError("Select at least one client before publishing");return}if(publish&&editor.schedule_mode==="later"&&!editor.starts_at){setError("Choose a start date and time for scheduled delivery");return}if(publish&&editor.end_mode==="at"&&!editor.ends_at){setError("Choose an end date and time or select no automatic end date");return}setSaving(true);setError(null);try{const method=editor.id?"PUT":"POST",url=editor.id?`/api/admin/campaigns/${editor.id}`:"/api/admin/campaigns";let r=await fetch(url,{method,credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload(editor))});let data=await r.json();if(!r.ok)throw new Error(data.detail||"Unable to save campaign");if(editor.imageFile){const fd=new FormData();fd.append("image",editor.imageFile);r=await fetch(`/api/admin/campaigns/${data.id}/image`,{method:"POST",credentials:"include",body:fd});data=await r.json();if(!r.ok)throw new Error(data.detail||"Unable to upload image")}if(publish){r=await fetch(`/api/admin/campaigns/${data.id}/publish`,{method:"POST",credentials:"include"});data=await r.json();if(!r.ok)throw new Error(data.detail||"Unable to publish");setNotice(data)}setEditor(null);await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
  const action=async(id,name)=>{const r=await fetch(`/api/admin/campaigns/${id}/${name}`,{method:"POST",credentials:"include"});const data=await r.json();if(!r.ok){setError(data.detail||"Action failed")}else if(name==="publish"){setNotice(data);setError(null)}await load()};
  const removeImage=async()=>{if(!editor.id){setEditor({...editor,imageFile:null});return}setSaving(true);try{const r=await fetch(`/api/admin/campaigns/${editor.id}/image`,{method:"DELETE",credentials:"include"});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Unable to remove image");setEditor({...editor,has_image:false,image_url:null,imageFile:null});await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
  const resetDismissals=async()=>{const r=await fetch(`/api/admin/campaigns/${resetTarget.id}/reset-popup-dismissals`,{method:"POST",credentials:"include"});if(!r.ok){const d=await r.json();setError(d.detail||"Reset failed")}setResetTarget(null);await load()};
  const remove=async()=>{const r=await fetch(`/api/admin/campaigns/${deleting.id}`,{method:"DELETE",credentials:"include"});if(!r.ok){const d=await r.json();setError(d.detail||"Delete failed")}setDeleting(null);await load()};
  if(loading)return <LoadingState/>; if(error&&!items.length)return <ErrorState error={error}/>;
  return <div><PageHeader title="Campaigns" subtitle="Create and publish client announcements for What’s New." actions={<Button onClick={()=>edit()}>Create campaign</Button>}/>
    {error&&<div className="alert-error mb-4">{error}</div>}
    {notice&&<div className="mb-4 rounded-xl border border-emerald-400/25 bg-emerald-500/10 p-4 text-sm text-emerald-100" role="status"><p className="font-semibold">Campaign published successfully.</p><p className="mt-2">Delivery: {notice.starts_at?"Scheduled for "+dt(notice.starts_at):"Eligible immediately"} · {notice.popup_enabled?"Popup enabled":"What’s New only"} · {notice.target_all_clients?"All active clients":notice.target_client_ids.length+" selected client(s)"}</p><p className="mt-1 text-emerald-200/80">Online clients may receive it within 30 seconds. Offline clients will receive it when they next open or log into the portal.</p></div>}
    <div className="space-y-3">{!items.length?<EmptyState>No campaigns created.</EmptyState>:items.map(c=><Card key={c.id} compact><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-white">{c.title}</h2><StatusBadge status={c.delivery_status}>{c.delivery_status.charAt(0).toUpperCase()+c.delivery_status.slice(1)}</StatusBadge><StatusBadge variant="info">{icons[c.campaign_type]} {c.campaign_type_label}</StatusBadge></div><dl className="mt-3 grid gap-x-6 gap-y-1 text-sm sm:grid-cols-2"><div><dt className="inline text-gray-500">Delivery: </dt><dd className="inline text-gray-300">{c.popup_enabled?"Popup + What’s New":"What’s New only"}</dd></div><div><dt className="inline text-gray-500">Audience: </dt><dd className="inline text-gray-300">{c.target_all_clients?"All active clients":c.target_client_ids.length+" selected client(s)"}</dd></div><div><dt className="inline text-gray-500">Effective start: </dt><dd className="inline text-gray-300">{c.starts_at?dt(c.starts_at):c.status==="published"?dt(c.published_at):"On publication"}</dd></div><div><dt className="inline text-gray-500">Effective end: </dt><dd className="inline text-gray-300">{c.ends_at?dt(c.ends_at):"No automatic end"}</dd></div><div><dt className="inline text-gray-500">Current recipient estimate: </dt><dd className="inline text-gray-300">{campaignRecipients(c)} active client(s)</dd></div><div><dt className="inline text-gray-500">Priority: </dt><dd className="inline text-gray-300">{c.priority}</dd></div></dl>{c.popup_enabled&&<p className="mt-2 text-xs text-gray-400">Popup metrics · {stats[c.id]?.displayed||0} displayed · {stats[c.id]?.dismissed||0} dismissed · {stats[c.id]?.opened||0} opened · {stats[c.id]?.action_clicked||0} action clicks</p>}</div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>setPreview(c)}>Preview</Button>{c.status!=="archived"&&<Button variant="secondary" onClick={()=>edit(c)}>Edit</Button>}{c.status==="draft"&&<Button onClick={()=>action(c.id,"publish")}>Publish</Button>}{c.status==="published"&&<Button variant="secondary" onClick={()=>action(c.id,"unpublish")}>Unpublish</Button>}{c.popup_enabled&&<Button variant="secondary" onClick={()=>setResetTarget(c)}>Reset dismissals</Button>}{c.status!=="archived"&&<Button variant="warning" onClick={()=>action(c.id,"archive")}>Archive</Button>}{c.status==="draft"&&<Button variant="danger" onClick={()=>setDeleting(c)}>Delete</Button>}</div></div></Card>)}</div>
    {editor&&<Modal maxWidth="max-w-3xl"><div className="max-h-[82dvh] overflow-y-auto pr-1"><h2 className="text-xl font-semibold text-white">{editor.id?"Edit campaign":"Create campaign"}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">
      <label className="form-label">Internal name<Input value={editor.internal_name} onChange={e=>setEditor({...editor,internal_name:e.target.value})}/></label><label className="form-label">Title<Input value={editor.title} onChange={e=>setEditor({...editor,title:e.target.value})}/></label>
      <label className="form-label sm:col-span-2">Subtitle<Input value={editor.subtitle||""} onChange={e=>setEditor({...editor,subtitle:e.target.value})}/></label>
      <label className="form-label">Type<Select value={editor.campaign_type} onChange={e=>setEditor({...editor,campaign_type:e.target.value})}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></label><label className="form-label">Priority<Input type="number" value={editor.priority} onChange={e=>setEditor({...editor,priority:e.target.value})}/></label>
      <label className="form-label sm:col-span-2">Content<Textarea rows="7" value={editor.body_content} onChange={e=>setEditor({...editor,body_content:e.target.value})}/></label>
      <label className="form-label">Price text<Input value={editor.price_text||""} onChange={e=>setEditor({...editor,price_text:e.target.value})}/></label><label className="form-label">Regular price text<Input value={editor.regular_price_text||""} onChange={e=>setEditor({...editor,regular_price_text:e.target.value})}/></label>
      <label className="form-label">CTA label<Input value={editor.call_to_action_label||""} onChange={e=>setEditor({...editor,call_to_action_label:e.target.value})}/></label><label className="form-label">CTA URL<Input value={editor.call_to_action_url||""} placeholder="/portal/... or https://..." onChange={e=>setEditor({...editor,call_to_action_url:e.target.value})}/></label><div><label className="form-label">Image (JPEG, PNG, WebP)<Input type="file" accept=".jpg,.jpeg,.png,.webp" onChange={e=>setEditor({...editor,imageFile:e.target.files[0]})}/></label>{(editor.has_image||editor.imageFile)&&<Button className="mt-2" variant="danger" disabled={saving} onClick={removeImage}>Remove image</Button>}</div>
      <fieldset className="sm:col-span-2 rounded-xl border border-white/10 bg-white/[.025] p-4"><legend className="px-1 text-sm font-semibold uppercase tracking-wider text-purple-300">Delivery</legend><div className="space-y-4"><div><p className="font-semibold text-white">Show in What’s New</p><p className="mt-1 text-sm text-gray-400">Every published campaign appears in What’s New.</p></div><label className="flex items-start gap-3 rounded-lg border border-white/10 p-3 text-sm text-white"><input className="mt-1" type="checkbox" checked={!!editor.popup_enabled} onChange={e=>setEditor({...editor,popup_enabled:e.target.checked})}/><span><span className="block font-semibold">Display once as popup notification</span><span className="mt-1 block text-gray-400">Shows once when first discovered at login or while the client is online. Online delivery may take up to 30 seconds.</span></span></label></div></fieldset>
      {editor.popup_enabled&&<label className="form-label sm:col-span-2">Popup summary<Input value={editor.popup_summary||""} onChange={e=>setEditor({...editor,popup_summary:e.target.value})}/></label>}
      <fieldset className="sm:col-span-2 rounded-xl border border-white/10 bg-white/[.025] p-4"><legend className="px-1 text-sm font-semibold uppercase tracking-wider text-purple-300">Schedule</legend><div className="space-y-3"><label className="flex items-start gap-3 rounded-lg border border-white/10 p-3 text-sm text-white"><input className="mt-1" type="radio" name="campaign-schedule" checked={editor.schedule_mode==="immediate"} onChange={()=>setEditor({...editor,schedule_mode:"immediate",starts_at:""})}/><span><span className="block font-semibold">Publish immediately</span><span className="mt-1 block text-gray-400">Becomes eligible using the server publication time.</span></span></label><label className="flex items-start gap-3 rounded-lg border border-white/10 p-3 text-sm text-white"><input className="mt-1" type="radio" name="campaign-schedule" checked={editor.schedule_mode==="later"} onChange={()=>setEditor({...editor,schedule_mode:"later"})}/><span><span className="block font-semibold">Schedule for later</span><span className="mt-1 block text-gray-400">Enter a date and time in your browser local timezone.</span></span></label>{editor.schedule_mode==="later"&&<label className="form-label block">Starts (local time)<Input type="datetime-local" value={editor.starts_at} onChange={e=>setEditor({...editor,starts_at:e.target.value})}/></label>}<div className="border-t border-white/10 pt-3"><label className="flex items-center gap-3 text-sm text-white"><input type="radio" name="campaign-end" checked={editor.end_mode==="none"} onChange={()=>setEditor({...editor,end_mode:"none",ends_at:""})}/>No automatic end date</label><label className="mt-3 flex items-center gap-3 text-sm text-white"><input type="radio" name="campaign-end" checked={editor.end_mode==="at"} onChange={()=>setEditor({...editor,end_mode:"at"})}/>End at selected date and time</label>{editor.end_mode==="at"&&<label className="form-label mt-3 block">Ends (local time)<Input type="datetime-local" value={editor.ends_at} onChange={e=>setEditor({...editor,ends_at:e.target.value})}/></label>}</div><p className="text-xs text-gray-500">Dates are entered in your local timezone and stored as UTC.</p>{shortWindow&&<p className="text-sm text-amber-300" role="alert">Warning: this campaign will expire less than one hour after it becomes eligible.</p>}</div></fieldset>
      <fieldset className="sm:col-span-2 rounded-xl border border-white/10 bg-white/[.025] p-4"><legend className="px-1 text-sm font-semibold uppercase tracking-wider text-purple-300">Audience</legend><div className="grid gap-3 sm:grid-cols-2"><label className="flex items-start gap-3 rounded-lg border border-white/10 p-3 text-sm text-white"><input className="mt-1" type="radio" name="campaign-audience" checked={editor.target_all_clients} onChange={()=>setEditor({...editor,target_all_clients:true,target_client_ids:[]})}/><span><span className="block font-semibold">All active clients</span><span className="mt-1 block text-gray-400">Deliver to every currently active client.</span></span></label><label className="flex items-start gap-3 rounded-lg border border-white/10 p-3 text-sm text-white"><input className="mt-1" type="radio" name="campaign-audience" checked={!editor.target_all_clients} onChange={()=>setEditor({...editor,target_all_clients:false})}/><span><span className="block font-semibold">Selected clients</span><span className="mt-1 block text-gray-400">Choose specific client accounts below.</span></span></label></div>{!editor.target_all_clients&&<div className="mt-3 grid gap-2 sm:grid-cols-2">{clients.map(c=><label key={c.id} className="flex items-center gap-2 rounded-lg border border-white/10 p-3 text-sm text-white"><input type="checkbox" checked={editor.target_client_ids.includes(c.id)} onChange={e=>setEditor({...editor,target_client_ids:e.target.checked?[...editor.target_client_ids,c.id]:editor.target_client_ids.filter(id=>id!==c.id)})}/><span>{c.name}<span className="ml-2 text-xs text-gray-500">{c.status}</span></span></label>)}</div>}</fieldset>
      <section className="sm:col-span-2 rounded-xl border border-purple-400/20 bg-purple-500/[.07] p-4" aria-live="polite"><h3 className="font-semibold text-white">Delivery summary</h3><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-gray-500">What’s New</dt><dd className="text-white">Yes</dd></div><div><dt className="text-gray-500">Popup notification</dt><dd className="text-white">{editor.popup_enabled?"Yes — shown once":"No"}</dd></div><div><dt className="text-gray-500">Audience</dt><dd className="text-white">{editor.target_all_clients?"All active clients":editor.target_client_ids.length+" selected client(s)"}</dd></div><div><dt className="text-gray-500">Eligible recipients</dt><dd className="text-white">{recipientCount+" active client(s)"}</dd></div><div className="sm:col-span-2"><dt className="text-gray-500">Schedule</dt><dd className="text-white">{editor.starts_at?"Starts "+dt(utcInput(editor.starts_at)):"Starts immediately"}{editor.ends_at?" · Ends "+dt(utcInput(editor.ends_at)):" · No end date"}</dd></div></dl>{!editor.target_all_clients&&!editor.target_client_ids.length&&<p className="mt-3 text-sm text-red-300">Select at least one client before publishing.</p>}</section>
    </div><div className="mt-6 flex flex-wrap justify-end gap-2"><Button variant="secondary" onClick={()=>setEditor(null)}>Cancel</Button><Button variant="secondary" onClick={()=>setPreview({...editor,campaign_type_label:labels[editor.campaign_type]})}>Preview</Button><Button disabled={saving} onClick={()=>save(false)}>Save draft</Button><Button disabled={saving||(!editor.target_all_clients&&!editor.target_client_ids.length)} onClick={()=>save(true)}>Save & publish</Button></div></div></Modal>}
    {preview&&<Modal maxWidth="max-w-xl"><article><StatusBadge variant="info">{icons[preview.campaign_type]} {preview.campaign_type_label||labels[preview.campaign_type]}</StatusBadge>{preview.image_url&&<img src={preview.image_url} alt="" className="mt-4 max-h-72 w-full rounded-xl object-cover"/>}<h2 className="mt-4 text-2xl font-bold text-white">{preview.title||"Campaign title"}</h2>{preview.subtitle&&<p className="mt-2 text-gray-400">{preview.subtitle}</p>}<p className="mt-5 whitespace-pre-line text-gray-200">{preview.body_content}</p>{preview.price_text&&<p className="mt-5 text-2xl font-bold text-purple-300">{preview.price_text} {preview.regular_price_text&&<span className="text-sm font-normal text-gray-500 line-through">{preview.regular_price_text}</span>}</p>}{preview.call_to_action_label&&<Button className="mt-5" disabled>{preview.call_to_action_label}</Button>}</article><div className="mt-6 flex justify-end"><Button variant="secondary" onClick={()=>setPreview(null)}>Close preview</Button></div></Modal>}
    {resetTarget&&<Modal><h2 className="text-lg font-semibold text-white">Reset popup dismissals?</h2><p className="mt-3 text-gray-300">This will allow users who dismissed “{resetTarget.title}” to receive it again when it is next discovered. Completed primary actions remain excluded.</p><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setResetTarget(null)}>Cancel</Button><Button variant="warning" onClick={resetDismissals}>Reset dismissals</Button></div></Modal>}
    {deleting&&<Modal><h2 className="text-lg font-semibold text-white">Delete draft campaign?</h2><p className="mt-3 text-gray-300">Permanently delete “{deleting.title}” and its associated media. This cannot be undone.</p><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setDeleting(null)}>Cancel</Button><Button variant="danger" onClick={remove}>Delete draft</Button></div></Modal>}
  </div>
}
