import { useCallback, useEffect, useState } from "react";
import { Button, Card, EmptyState, ErrorState, Input, LoadingState, Modal, PageHeader, Select, StatusBadge, Textarea } from "../components/ui";

const blank = { internal_name:"", title:"", subtitle:"", campaign_type:"announcement", body_content:"", price_text:"", regular_price_text:"", call_to_action_label:"", priority:0, starts_at:"", ends_at:"", target_all_clients:true, target_client_ids:[], popup_enabled:false, popup_summary:"", call_to_action_url:"" };
const labels = { announcement:"Announcement", promotion:"Promotion", new_service:"New Service", maintenance_notice:"Maintenance Notice", tip:"Tip", featured_project:"Featured Project", important_notice:"Important Notice" };
const icons = { announcement:"✦", promotion:"%", new_service:"+", maintenance_notice:"⚙", tip:"i", featured_project:"★", important_notice:"!" };
const dt = value => value ? new Date(value).toLocaleString() : "Not set";

export default function Campaigns() {
  const [items,setItems]=useState([]), [clients,setClients]=useState([]), [loading,setLoading]=useState(true);
  const [error,setError]=useState(null), [editor,setEditor]=useState(null), [preview,setPreview]=useState(null), [deleting,setDeleting]=useState(null), [resetTarget,setResetTarget]=useState(null), [saving,setSaving]=useState(false), [stats,setStats]=useState({});
  const load=useCallback(async()=>{try{const [a,b,s]=await Promise.all([fetch("/api/admin/campaigns",{credentials:"include"}),fetch("/api/admin/campaign-target-clients",{credentials:"include"}),fetch("/api/admin/campaign-popup-stats",{credentials:"include"})]);if(!a.ok||!b.ok||!s.ok)throw new Error("Unable to load campaigns");setItems((await a.json()).campaigns);setClients(await b.json());setStats((await s.json()).campaigns||{});setError(null)}catch(e){setError(e.message)}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);
  const edit=item=>setEditor(item?{...item,starts_at:item.starts_at?.slice(0,16)||"",ends_at:item.ends_at?.slice(0,16)||""}:{...blank});
  const payload=form=>({...form,priority:Number(form.priority)||0,starts_at:form.starts_at||null,ends_at:form.ends_at||null});
  const save=async(publish=false)=>{setSaving(true);setError(null);try{const method=editor.id?"PUT":"POST",url=editor.id?`/api/admin/campaigns/${editor.id}`:"/api/admin/campaigns";let r=await fetch(url,{method,credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload(editor))});let data=await r.json();if(!r.ok)throw new Error(data.detail||"Unable to save campaign");if(editor.imageFile){const fd=new FormData();fd.append("image",editor.imageFile);r=await fetch(`/api/admin/campaigns/${data.id}/image`,{method:"POST",credentials:"include",body:fd});data=await r.json();if(!r.ok)throw new Error(data.detail||"Unable to upload image")}if(publish){r=await fetch(`/api/admin/campaigns/${data.id}/publish`,{method:"POST",credentials:"include"});data=await r.json();if(!r.ok)throw new Error(data.detail||"Unable to publish")}setEditor(null);await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
  const action=async(id,name)=>{const r=await fetch(`/api/admin/campaigns/${id}/${name}`,{method:"POST",credentials:"include"});if(!r.ok){const d=await r.json();setError(d.detail||"Action failed")}await load()};
  const removeImage=async()=>{if(!editor.id){setEditor({...editor,imageFile:null});return}setSaving(true);try{const r=await fetch(`/api/admin/campaigns/${editor.id}/image`,{method:"DELETE",credentials:"include"});const d=await r.json();if(!r.ok)throw new Error(d.detail||"Unable to remove image");setEditor({...editor,has_image:false,image_url:null,imageFile:null});await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
  const resetDismissals=async()=>{const r=await fetch(`/api/admin/campaigns/${resetTarget.id}/reset-popup-dismissals`,{method:"POST",credentials:"include"});if(!r.ok){const d=await r.json();setError(d.detail||"Reset failed")}setResetTarget(null);await load()};
  const remove=async()=>{const r=await fetch(`/api/admin/campaigns/${deleting.id}`,{method:"DELETE",credentials:"include"});if(!r.ok){const d=await r.json();setError(d.detail||"Delete failed")}setDeleting(null);await load()};
  if(loading)return <LoadingState/>; if(error&&!items.length)return <ErrorState error={error}/>;
  return <div><PageHeader title="Campaigns" subtitle="Create and publish client announcements for What’s New." actions={<Button onClick={()=>edit()}>Create campaign</Button>}/>
    {error&&<div className="alert-error mb-4">{error}</div>}
    <div className="space-y-3">{!items.length?<EmptyState>No campaigns created.</EmptyState>:items.map(c=><Card key={c.id} compact><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-white">{c.title}</h2><StatusBadge status={c.status}>{c.status}</StatusBadge><StatusBadge variant="info">{icons[c.campaign_type]} {c.campaign_type_label}</StatusBadge></div><p className="mt-1 text-sm text-gray-400">{c.target_all_clients?"All active clients":`${c.target_client_ids.length} selected client(s)`} · Priority {c.priority}</p><p className="mt-1 text-xs text-gray-500">{dt(c.starts_at)} – {dt(c.ends_at)} · {c.has_image?"Image attached":"No image"}</p>{c.popup_enabled&&<p className="mt-2 text-xs text-gray-400">Login popup · {stats[c.id]?.displayed||0} displayed · {stats[c.id]?.dismissed||0} dismissed · {stats[c.id]?.opened||0} opened · {stats[c.id]?.action_clicked||0} action clicks</p>}</div><div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>setPreview(c)}>Preview</Button>{c.status!=="archived"&&<Button variant="secondary" onClick={()=>edit(c)}>Edit</Button>}{c.status==="draft"&&<Button onClick={()=>action(c.id,"publish")}>Publish</Button>}{c.status==="published"&&<Button variant="secondary" onClick={()=>action(c.id,"unpublish")}>Unpublish</Button>}{c.popup_enabled&&<Button variant="secondary" onClick={()=>setResetTarget(c)}>Reset dismissals</Button>}{c.status!=="archived"&&<Button variant="warning" onClick={()=>action(c.id,"archive")}>Archive</Button>}{c.status==="draft"&&<Button variant="danger" onClick={()=>setDeleting(c)}>Delete</Button>}</div></div></Card>)}</div>
    {editor&&<Modal maxWidth="max-w-3xl"><div className="max-h-[82dvh] overflow-y-auto pr-1"><h2 className="text-xl font-semibold text-white">{editor.id?"Edit campaign":"Create campaign"}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">
      <label className="form-label">Internal name<Input value={editor.internal_name} onChange={e=>setEditor({...editor,internal_name:e.target.value})}/></label><label className="form-label">Title<Input value={editor.title} onChange={e=>setEditor({...editor,title:e.target.value})}/></label>
      <label className="form-label sm:col-span-2">Subtitle<Input value={editor.subtitle||""} onChange={e=>setEditor({...editor,subtitle:e.target.value})}/></label>
      <label className="form-label">Type<Select value={editor.campaign_type} onChange={e=>setEditor({...editor,campaign_type:e.target.value})}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></label><label className="form-label">Priority<Input type="number" value={editor.priority} onChange={e=>setEditor({...editor,priority:e.target.value})}/></label>
      <label className="form-label sm:col-span-2">Content<Textarea rows="7" value={editor.body_content} onChange={e=>setEditor({...editor,body_content:e.target.value})}/></label>
      <label className="form-label">Price text<Input value={editor.price_text||""} onChange={e=>setEditor({...editor,price_text:e.target.value})}/></label><label className="form-label">Regular price text<Input value={editor.regular_price_text||""} onChange={e=>setEditor({...editor,regular_price_text:e.target.value})}/></label>
      <label className="form-label">CTA label<Input value={editor.call_to_action_label||""} onChange={e=>setEditor({...editor,call_to_action_label:e.target.value})}/></label><label className="form-label">CTA URL<Input value={editor.call_to_action_url||""} placeholder="/portal/... or https://..." onChange={e=>setEditor({...editor,call_to_action_url:e.target.value})}/></label><div><label className="form-label">Image (JPEG, PNG, WebP)<Input type="file" accept=".jpg,.jpeg,.png,.webp" onChange={e=>setEditor({...editor,imageFile:e.target.files[0]})}/></label>{(editor.has_image||editor.imageFile)&&<Button className="mt-2" variant="danger" disabled={saving} onClick={removeImage}>Remove image</Button>}</div>
      <label className="sm:col-span-2 flex items-center gap-3 text-sm text-white"><input type="checkbox" checked={!!editor.popup_enabled} onChange={e=>setEditor({...editor,popup_enabled:e.target.checked})}/>Show as login popup</label>
      {editor.popup_enabled&&<label className="form-label sm:col-span-2">Popup summary<Input value={editor.popup_summary||""} onChange={e=>setEditor({...editor,popup_summary:e.target.value})}/></label>}
      <label className="form-label">Starts<Input type="datetime-local" value={editor.starts_at} onChange={e=>setEditor({...editor,starts_at:e.target.value})}/></label><label className="form-label">Ends<Input type="datetime-local" value={editor.ends_at} onChange={e=>setEditor({...editor,ends_at:e.target.value})}/></label>
      <label className="sm:col-span-2 flex items-center gap-3 text-sm text-white"><input type="checkbox" checked={editor.target_all_clients} onChange={e=>setEditor({...editor,target_all_clients:e.target.checked,target_client_ids:e.target.checked?[]:editor.target_client_ids})}/>Target all active clients</label>
      {!editor.target_all_clients&&<fieldset className="sm:col-span-2"><legend className="form-label">Selected clients</legend><div className="grid gap-2 sm:grid-cols-2">{clients.map(c=><label key={c.id} className="flex items-center gap-2 rounded-lg border border-white/10 p-3 text-sm text-white"><input type="checkbox" checked={editor.target_client_ids.includes(c.id)} onChange={e=>setEditor({...editor,target_client_ids:e.target.checked?[...editor.target_client_ids,c.id]:editor.target_client_ids.filter(id=>id!==c.id)})}/>{c.name}</label>)}</div></fieldset>}
    </div><div className="mt-6 flex flex-wrap justify-end gap-2"><Button variant="secondary" onClick={()=>setEditor(null)}>Cancel</Button><Button variant="secondary" onClick={()=>setPreview({...editor,campaign_type_label:labels[editor.campaign_type]})}>Preview</Button><Button disabled={saving} onClick={()=>save(false)}>Save draft</Button><Button disabled={saving} onClick={()=>save(true)}>Save & publish</Button></div></div></Modal>}
    {preview&&<Modal maxWidth="max-w-xl"><article><StatusBadge variant="info">{icons[preview.campaign_type]} {preview.campaign_type_label||labels[preview.campaign_type]}</StatusBadge>{preview.image_url&&<img src={preview.image_url} alt="" className="mt-4 max-h-72 w-full rounded-xl object-cover"/>}<h2 className="mt-4 text-2xl font-bold text-white">{preview.title||"Campaign title"}</h2>{preview.subtitle&&<p className="mt-2 text-gray-400">{preview.subtitle}</p>}<p className="mt-5 whitespace-pre-line text-gray-200">{preview.body_content}</p>{preview.price_text&&<p className="mt-5 text-2xl font-bold text-purple-300">{preview.price_text} {preview.regular_price_text&&<span className="text-sm font-normal text-gray-500 line-through">{preview.regular_price_text}</span>}</p>}{preview.call_to_action_label&&<Button className="mt-5" disabled>{preview.call_to_action_label}</Button>}</article><div className="mt-6 flex justify-end"><Button variant="secondary" onClick={()=>setPreview(null)}>Close preview</Button></div></Modal>}
    {resetTarget&&<Modal><h2 className="text-lg font-semibold text-white">Reset popup dismissals?</h2><p className="mt-3 text-gray-300">This will allow users who dismissed “{resetTarget.title}” to receive it again on a future login. Completed primary actions remain excluded.</p><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setResetTarget(null)}>Cancel</Button><Button variant="warning" onClick={resetDismissals}>Reset dismissals</Button></div></Modal>}
    {deleting&&<Modal><h2 className="text-lg font-semibold text-white">Delete draft campaign?</h2><p className="mt-3 text-gray-300">Permanently delete “{deleting.title}” and its associated media. This cannot be undone.</p><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setDeleting(null)}>Cancel</Button><Button variant="danger" onClick={remove}>Delete draft</Button></div></Modal>}
  </div>
}
