import { useEffect, useState } from "react";
import { BookOpen, Upload, Eye, Trash2 } from "lucide-react";
import { Button, Card, EmptyState, ErrorState, LoadingState, Modal, PageHeader, StatusBadge } from "../components/ui";

const blank={title:"",description:"",category:"Getting Started",visibility_mode:"all",client_ids:[],published:false,featured:false,display_order:0,file:null};
export default function ClientGuides(){
 const [guides,setGuides]=useState([]),[clients,setClients]=useState([]),[editor,setEditor]=useState(null),[error,setError]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[deleting,setDeleting]=useState(null);
 const load=async()=>{try{const [g,c]=await Promise.all([fetch('/api/admin/client-guides',{credentials:'include'}),fetch('/api/clients',{credentials:'include'})]);if(!g.ok||!c.ok)throw new Error('Unable to load Client Guides');setGuides(await g.json());setClients(await c.json());setError(null)}catch(e){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{load()},[]);
 const edit=g=>setEditor(g?{...g,file:null}:{...blank});
 const save=async()=>{if(!editor.title.trim()||!editor.category.trim()){setError('Title and category are required');return}if(!editor.id&&!editor.file){setError('Choose a guide file');return}if(editor.visibility_mode==='selected'&&!editor.client_ids.length){setError('Select at least one client');return}setSaving(true);setError(null);try{let r;if(editor.id){r=await fetch(`/api/admin/client-guides/${editor.id}`,{method:'PUT',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({...editor,file:undefined,preview_url:undefined,download_url:undefined,original_file_name:undefined,mime_type:undefined,file_size:undefined,created_at:undefined,updated_at:undefined,id:undefined})});if(!r.ok)throw new Error((await r.json()).detail||'Unable to update guide');if(editor.file){const fd=new FormData();fd.append('guide_file',editor.file);r=await fetch(`/api/admin/client-guides/${editor.id}/file`,{method:'POST',credentials:'include',body:fd});if(!r.ok)throw new Error((await r.json()).detail||'Unable to replace file')}}else{const fd=new FormData();['title','description','category','visibility_mode','published','featured','display_order'].forEach(k=>fd.append(k,editor[k]));fd.append('client_ids',editor.client_ids.join(','));fd.append('guide_file',editor.file);r=await fetch('/api/admin/client-guides',{method:'POST',credentials:'include',body:fd});if(!r.ok)throw new Error((await r.json()).detail||'Unable to create guide')}setEditor(null);await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 const remove=async()=>{const r=await fetch(`/api/admin/client-guides/${deleting.id}`,{method:'DELETE',credentials:'include'});if(!r.ok){setError((await r.json()).detail||'Unable to delete guide');return}setDeleting(null);await load()};
 if(loading)return <LoadingState/>;if(error&&!guides.length)return <ErrorState error={error}/>;
 return <div className="space-y-6"><PageHeader title="Client Guides" subtitle="Publish protected visual help for client portal users." action={<Button onClick={()=>edit(null)}><Upload className="h-4 w-4"/>Upload guide</Button>}/>{error&&<div className="alert-error" role="alert">{error}</div>}
 {guides.length?<div className="grid gap-4">{guides.map(g=><Card key={g.id}><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap gap-2"><StatusBadge status={g.published?'active':'inactive'}>{g.published?'Published':'Unpublished'}</StatusBadge>{g.featured&&<StatusBadge>Featured</StatusBadge>}<span className="text-xs text-gray-500">Order {g.display_order}</span></div><h2 className="mt-3 text-lg font-semibold text-white">{g.title}</h2><p className="mt-1 text-sm text-gray-400">{g.category} · {g.visibility_mode==='all'?'All clients':`${g.client_ids.length} selected client(s)`}</p><p className="mt-2 text-sm text-gray-500">{g.original_file_name}</p></div><div className="flex flex-wrap gap-2"><Button as="a" href={g.preview_url} target="_blank" variant="secondary"><Eye className="h-4 w-4"/>Preview</Button><Button onClick={()=>edit(g)} variant="secondary">Edit</Button><Button onClick={()=>setDeleting(g)} variant="danger"><Trash2 className="h-4 w-4"/>Delete</Button></div></div></Card>)}</div>:<EmptyState><BookOpen className="mx-auto mb-3 h-8 w-8"/>No client guides have been uploaded.</EmptyState>}
 {editor&&<Modal maxWidth="max-w-3xl"><h2 className="text-xl font-semibold text-white">{editor.id?'Edit guide':'Upload guide'}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm text-gray-300">Title<input className="form-input mt-2" value={editor.title} onChange={e=>setEditor({...editor,title:e.target.value})}/></label><label className="text-sm text-gray-300">Category<input className="form-input mt-2" value={editor.category} onChange={e=>setEditor({...editor,category:e.target.value})}/></label><label className="sm:col-span-2 text-sm text-gray-300">Short description<textarea className="form-input mt-2" rows="3" value={editor.description} onChange={e=>setEditor({...editor,description:e.target.value})}/></label><label className="text-sm text-gray-300">File {editor.id&&'(optional replacement)'}<input type="file" accept="image/png,image/jpeg,image/webp,application/pdf" className="form-input mt-2" onChange={e=>setEditor({...editor,file:e.target.files[0]||null})}/></label><label className="text-sm text-gray-300">Display order<input type="number" className="form-input mt-2" value={editor.display_order} onChange={e=>setEditor({...editor,display_order:Number(e.target.value)})}/></label><label className="text-sm text-gray-300">Visibility<select className="form-input mt-2" value={editor.visibility_mode} onChange={e=>setEditor({...editor,visibility_mode:e.target.value})}><option value="all">All clients</option><option value="selected">Selected clients</option></select></label><div className="flex flex-wrap items-center gap-5 text-sm text-gray-300"><label><input type="checkbox" checked={editor.published} onChange={e=>setEditor({...editor,published:e.target.checked})}/> Published</label><label><input type="checkbox" checked={editor.featured} onChange={e=>setEditor({...editor,featured:e.target.checked})}/> Featured</label></div>{editor.visibility_mode==='selected'&&<fieldset className="sm:col-span-2 rounded-xl border border-white/10 p-4"><legend className="px-2 text-sm text-gray-300">Selected clients</legend><div className="grid gap-2 sm:grid-cols-2">{clients.map(c=><label key={c.id} className="text-sm text-gray-300"><input type="checkbox" checked={editor.client_ids.includes(c.id)} onChange={e=>setEditor({...editor,client_ids:e.target.checked?[...editor.client_ids,c.id]:editor.client_ids.filter(id=>id!==c.id)})}/> {c.name}</label>)}</div></fieldset>}</div><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setEditor(null)}>Cancel</Button><Button disabled={saving} onClick={save}>{saving?'Saving…':'Save guide'}</Button></div></Modal>}
 {deleting&&<Modal maxWidth="max-w-lg"><h2 className="text-lg font-semibold text-white">Delete guide?</h2><p className="mt-3 text-gray-300">This permanently removes “{deleting.title}”, its assignments and managed file.</p><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setDeleting(null)}>Cancel</Button><Button variant="danger" onClick={remove}>Permanently delete</Button></div></Modal>}</div>;
}
